# Generated by Django 5.2.12 on 2026-05-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
