# Generated by Django 5.2.12 on 2026-05-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultationrequest_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('goal', models.CharField(choices=[('buy', 'Купить'), ('sell', 'Продать')], max_length=16, verbose_name='Цель')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('cancelled', 'Отменена')], default='new', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка на оценку',
                'verbose_name_plural': 'Заявки на оценку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='message',
        ),
    ]
