# Generated by Django 5.2.12 on 2026-05-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_evaluationrequest_remove_consultationrequest_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextStepRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('task_description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('cancelled', 'Отменена')], default='new', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка «Подскажем следующий шаг»',
                'verbose_name_plural': 'Заявки «Подскажем следующий шаг»',
                'ordering': ['-created_at'],
            },
        ),
    ]
