# Generated by Django 5.2.12 on 2026-05-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_nextsteprequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationRequest',
        ),
    ]
