# Generated by Django 5.2.12 on 2026-04-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пример работы', 'verbose_name_plural': 'Примеры работ'},
        ),
        migrations.AlterModelOptions(
            name='portfolioitemimage',
            options={'ordering': ['id'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='portfolioitemimage',
            name='order',
        ),
    ]
