# Generated by Django 5.2.12 on 2026-03-10 08:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_category_name_ru'),
        ('districts', '0003_district_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Активно'), (2, 'На модерации'), (3, 'Продано'), (4, 'В архиве')], default=0, verbose_name='Статус')),
                ('price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('USD', '$'), ('UZS', 'сум')], default='USD', max_length=3, verbose_name='Валюта')),
                ('num_rooms', models.PositiveSmallIntegerField(default=1, verbose_name='Количество комнат')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Общая площадь (м²)')),
                ('area_living', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Жилая площадь (м²)')),
                ('floor_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Всего этажей')),
                ('ceiling_height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Высота потолков (м)')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('renovation_type', models.CharField(blank=True, choices=[('renovation', 'Ремонт'), ('pre_finished', 'Предчистовая'), ('shell', 'Коробка'), ('none', 'Без ремонта')], default='none', max_length=20, verbose_name='Тип ремонта')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('address_uz', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('seller_name', models.CharField(blank=True, max_length=255, verbose_name='Имя продавца')),
                ('seller_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон продавца')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='categories.category', verbose_name='Категория')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='districts.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='advertisements/%Y/%m/', verbose_name='Изображение')),
                ('ordering', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisements.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Изображение объявления',
                'verbose_name_plural': 'Изображения объявлений',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
