# Generated by Django 5.2.12 on 2026-03-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisementcharacteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisementcharacteristic',
            options={'ordering': ['id'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterModelOptions(
            name='advertisementimage',
            options={'ordering': ['id'], 'verbose_name': 'Изображение объявления', 'verbose_name_plural': 'Изображения объявлений'},
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='seller_phone',
        ),
        migrations.RemoveField(
            model_name='advertisementcharacteristic',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='advertisementimage',
            name='ordering',
        ),
    ]
