# Generated by Django 5.2.12 on 2026-03-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_advertisementcharacteristic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='advertisements/covers/%Y/%m/', verbose_name='Фото заставки'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
    ]
