# Generated by Django 5.2.12 on 2026-03-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0004_advertisement_cover_image_advertisement_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='video_url',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, upload_to='advertisements/videos/%Y/%m/', verbose_name='Видео'),
        ),
    ]
