# Generated by Django 5.2.12 on 2026-03-12 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_replace_video_url_with_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='moderation_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ожидает модерации'), (1, 'Одобрено'), (2, 'Отклонено')], default=0, verbose_name='Модерация'),
        ),
    ]
