# Generated by Django 5.2.12 on 2026-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_advertisement_is_hot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, help_text='Пусто при создании — сформируется из категории, района, цены и числа комнат.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
