# Generated by Django 5.2.12 on 2026-04-07 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0008_advertisement_slug_auto_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='deal_type',
            field=models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Покупка')], db_index=True, default='sale', max_length=10, verbose_name='Тип сделки'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='housing_market',
            field=models.CharField(choices=[('new_building', 'Новостройка'), ('secondary', 'Вторичка')], db_index=True, default='secondary', help_text='Новостройка или вторичка', max_length=20, verbose_name='Рынок жилья'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='num_rooms',
            field=models.SmallIntegerField(default=1, help_text='0 — студия', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество комнат'),
        ),
    ]
