# Generated by Django 5.2.12 on 2026-04-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0009_advertisement_filters_deal_market_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='developer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='finishing_type',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('without', 'Без отделки'), ('rough', 'Черновая'), ('pre_finish', 'Предчистовая'), ('fine', 'Чистовая')], default='', max_length=20, verbose_name='Отделка'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='has_commission',
            field=models.BooleanField(default=False, help_text='False — «комиссионные нет».', verbose_name='Есть комиссия'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='housing_class',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('economy', 'Эконом'), ('comfort', 'Комфорт'), ('business', 'Бизнес'), ('premium', 'Премиум')], default='', max_length=20, verbose_name='Класс жилья'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_furnished',
            field=models.BooleanField(blank=True, null=True, verbose_name='Меблирована'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='landmark',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ориентир'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='landmark_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ориентир'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='landmark_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ориентир'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='parking_type',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('none', 'Нет'), ('open', 'Открытая'), ('underground', 'Подземная'), ('covered', 'Крытая'), ('multilevel', 'Многоуровневая')], default='', max_length=20, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='residential_complex_name',
            field=models.CharField(blank=True, help_text='Актуально для новостроек: название ЖК.', max_length=255, verbose_name='Жилой комплекс (ЖК)'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='street_intersection',
            field=models.CharField(blank=True, help_text='Кратко: какие улицы пересекаются (без дублирования полного адреса).', max_length=500, verbose_name='Пересечение улиц'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='street_intersection_ru',
            field=models.CharField(blank=True, help_text='Кратко: какие улицы пересекаются (без дублирования полного адреса).', max_length=500, null=True, verbose_name='Пересечение улиц'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='street_intersection_uz',
            field=models.CharField(blank=True, help_text='Кратко: какие улицы пересекаются (без дублирования полного адреса).', max_length=500, null=True, verbose_name='Пересечение улиц'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='renovation_type',
            field=models.CharField(blank=True, choices=[('euro', 'Евроремонт'), ('renovation', 'Ремонт'), ('pre_finished', 'Предчистовая'), ('shell', 'Коробка'), ('none', 'Без ремонта')], default='none', max_length=20, verbose_name='Тип ремонта'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, help_text='Пусто при создании — из категории, района, цены, комнат и валюты.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
