# Generated by Django 5.2.13 on 2026-04-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0011_renovation_type_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renovationtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='renovationtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
