# Generated by Django 5.2.12 on 2026-05-02 05:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0012_alter_renovationtype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена в долларах. При сохранении пересчитывается в сумы по курсу ЦБ.', max_digits=12, null=True, verbose_name='Цена в USD'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('UZS', 'сум')], default='UZS', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='Заполняется автоматически из price_usd по последнему курсу USD.', max_digits=14, verbose_name='Цена в UZS (авто)'),
        ),
    ]
