# Generated by Django 5.2.13 on 2026-05-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0013_advertisement_price_usd_alter_advertisement_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, help_text='Пусто при создании — из категории, района, цены в USD (`price_usd`), комнат и «usd» в конце; если `price_usd` не задан — из `price` и `currency`.', max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
